In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data_base_dir = '../../datasets/Movielens/'
data_dir2 = data_base_dir + 'Movielens Latest/ml-latest/'
data_dir = data_base_dir + 'ml-20m/'

genome_scores = data_dir + 'genome-scores.csv'
genome_tags = data_dir + 'genome-tags.csv'
movies = data_dir + 'movies.csv'
ratings = data_dir + 'ratings.csv'
tags = data_dir + 'tags.csv'

ratings_df = pd.read_csv(ratings, usecols=range(3), dtype={'userId':np.int64, 'movieId':np.int64, 'rating':np.float64}, low_memory=False)
ratings_df

          userId  movieId  rating
0              1        2     3.5
1              1       29     3.5
2              1       32     3.5
3              1       47     3.5
4              1       50     3.5
5              1      112     3.5
6              1      151     4.0
7              1      223     4.0
8              1      253     4.0
9              1      260     4.0
10             1      293     4.0
11             1      296     4.0
12             1      318     4.0
13             1      337     3.5
14             1      367     3.5
15             1      541     4.0
16             1      589     3.5
17             1      593     3.5
18             1      653     3.0
19             1      919     3.5
20             1      924     3.5
21             1     1009     3.5
22             1     1036     4.0
23             1     1079     4.0
24             1     1080     3.5
25             1     1089     3.5
26             1     1090     4.0
27             1     1097     4.0
28             1     1136     3.5
29             1     1193     3.5
...          ...      ...     ...
20000233  138493    50872     3.5
20000234  138493    51086     3.5
20000235  138493    51662     4.5
20000236  138493    51884     4.5
20000237  138493    52579     4.0
20000238  138493    52975     4.0
20000239  138493    53123     4.0
20000240  138493    53125     3.0
20000241  138493    53322     4.0
20000242  138493    53464     4.0
20000243  138493    53996     4.5
20000244  138493    55269     5.0
20000245  138493    55814     5.0
20000246  138493    56757     3.0
20000247  138493    56801     3.0
20000248  138493    58879     4.5
20000249  138493    59315     4.0
20000250  138493    59725     3.0
20000251  138493    59784     5.0
20000252  138493    60069     4.0
20000253  138493    60816     4.5
20000254  138493    61160     4.0
20000255  138493    65682     4.5
20000256  138493    66762     4.5
20000257  138493    68319     4.5
20000258  138493    68954     4.5
20000259  138493    69526     4.5
20000260  138493    69644     3.0
20000261  138493    70286     5.0
20000262  138493    71619     2.5

[20000263 rows x 3 columns]